[package]
name = "fibre-components"
version = "0.1.0"
edition = "2021"

authors = [
    "storycraft <storycraft@pancake.sh>"
]
license = "Apache-2.0"
repository = "https://github.com/storycraft/fibre"

[dependencies]
